# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='confirm',
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children')], max_length=20, null=True),
        ),
    ]
